# Generated by Django 4.1 on 2022-08-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="meetup",
            name="participants",
            field=models.ManyToManyField(blank=True, to="meetups.participant"),
        ),
    ]
