# Generated by Django 4.1 on 2022-08-17 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("meetups", "0005_alter_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2022-09-26"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
